### ISSUE TITLE
Text characters not render as expected

### ISSUE THREAD

**Issue by adrianengine** [WebWeWant/webwewant.fyi#21] opened 2019-11-12 20:31 UTC
Issue:
After submitting the form, the [response page](https://webwewant.fyi/submitted/), the browser renders some characters like there was not utf-8 enabled.

Browser/OS:
Firefox 71.0b8 (64-bit)/MacOS Mojave v10.14.6 

Screenshot:
![image](https://user-images.githubusercontent.com/1206844/68708030-e37f6e00-0560-11ea-8da3-ea7621b14713.png)

**Comment by aarongustafson** [comment] 2019-11-26 00:40
Weird. I see the `<meta charset="utf-8">` tag in there… I’ll investigate further.

**Comment by aarongustafson** [comment] 2019-11-26 00:42
I just booted up the Dev Edition of FF71 on Mojave & don’t see the issue. Can you conform it is still happening @adrianengine?

**Comment by bkardell** [comment] 2019-11-26 02:04
it would be great to capture the har or something if you can make it happen again (even just the HTML might be enough)

**Comment by bkardell** [comment] 2019-11-26 02:14
also doesn't happen for me on Version 70.0.1 (64-bit) for Linux (Ubuntu)

**Comment by adrianengine** [comment] 2019-11-26 04:40
Hi! It is still happening.
If I visit the [url](https://webwewant.fyi/submitted/) directly it displays good. But If I fill the form, send it and get redirected; the bug is visible.

Try making the user flow from the homepage.
After submit the form, there is a <script> tag injected on the <head>, probably causing the issue.

Here is the HAR file as a TXT.
[webwewant.fyi_Archive [19-11-25 23-31-16].txt](https://github.com/WebWeWant/webwewant.fyi/files/3890047/webwewant.fyi_Archive.19-11-25.23-31-16.txt)

Hope it helps!

**Comment by aarongustafson** [comment] 2019-11-26 19:24
@adrianengine Thanks! Makes me think Netlify is doing something weird. I'll look into it.

**Comment by aarongustafson** [comment] 2019-11-26 20:47
@adrianengine Can you test again? I am forcing all html to be delivered with a charset of utf-8 via headers now. I am not seeing the issue in Chromium.

**Comment by adrianengine** [comment] 2019-11-27 03:12
Hi @aarongustafson,
I've tested again, with same result. 😞

**Comment by Malvoz** [comment] 2019-11-27 12:30
FWIW I tested this without clearing site data (no `charset=UTF-8` in `Content-Type`) and also after clearing site data (with `charset=UTF-8`) and didn't have this issue in any of the cases, on Chrome 78.0.3904.108, Windows.

**Comment by aarongustafson** [comment] 2020-02-11 20:12
@philhawksworth @sdras Any chance you could bubble this up to the Netlify platform folks? Seems like an issue with the response not getting properly encoded.

**Comment by zachleat** [comment] 2020-02-11 21:43
Was able to duplicate this on Firefox 72 on Mac OS Catalina

Broken `POST` form submission is missing utf-8 in the content type, fwiw:
![image](https://user-images.githubusercontent.com/39355/74282029-16163f80-4ce5-11ea-9d38-225a59ff4d82.png)

Standard working `GET` request to the url has it:
![image](https://user-images.githubusercontent.com/39355/74282106-30501d80-4ce5-11ea-9e0f-7dc2efc192c7.png)

**Comment by aarongustafson** [comment] 2020-02-11 22:01
@zachleat Thanks for taking a look!

So even though the result page itself declares itself to be UTF-8, that’s not honored by Netlify? I am currently setting the character encoding in both the `meta` and in the `netlify.toml`. It seems like either (or both) of those should be influencing how it gets interpreted. Is there some additional Netlify magic I need to learn to correct this?

**Comment by philhawksworth** [comment] 2020-02-12 14:42
Hmm. Curious!

It might be useful to take this question over to https://community.netlify.com where more people have their eyes on things.

I think I may have spotted a related topic which has yielded a bug report.

https://community.netlify.com/t/firefox-dont-apply-encoding-after-form-redirect/2211/4

**Comment by aarongustafson** [comment] 2020-02-12 21:31
Looks like that’s related @philhawksworth, thank you.

Is there any way to force the redirect to use the UTF-8 header via the TOML? Given that I have a rule that does that in place for .html, my guess is that is somehow ignored on the redirect.

**Comment by Malvoz** [comment] 2020-02-12 21:40
An uneducated thought: could the presence of [BOM](https://www.w3.org/International/questions/qa-byte-order-mark) help in this case?

**Comment by jakub-g** [comment] 2020-04-04 18:08
The problem is that the first thing in <head> is a huge `<script>` which starts with `var FormSubmission = ...`

the <meta charset> is only after that script and out of initial 1024 chars.

![image](https://user-images.githubusercontent.com/1437027/78458208-d0a43c00-76af-11ea-951a-931e71abfac0.png)

**Comment by jakub-g** [comment] 2020-04-05 16:16
I searched on github in this repo for `FormSubmission` but I don't find it, so I guess it's some backend magic injecting the inline `<script>` as a first child to `head`, which leads to the issue.

**Comment by aarongustafson** [comment] 2020-04-08 19:27
> I searched on github in this repo for `FormSubmission` but I don't find it, so I guess it's some backend magic injecting the inline `<script>` as a first child to `head`, which leads to the issue.

Yeah, it’s a Netlify issue.

**Comment by aarongustafson** [comment] 2020-10-23 22:27
Looks like this was resolved in June: https://community.netlify.com/t/firefox-dont-apply-encoding-after-form-redirect/2211/15

**Closed by aarongustafson** 2020-10-23 22:27 UTC
Labels: bug
